# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Alissia Kirss
title: Quantitative Finance Graduate/ Post-Graduate Student
email: alissiahrus@gmail.com
# website: https://github.com/alihru

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username:  alihru
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"


# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello, my name is Alissia. I am originally from Estonia, where I have spent the first 12 years of my life. 
  Afterwards my family and I moved to Ireland. I went to school in the beatuiful coastal town of Sligo. 
  Afterwards I decided that I want to study mathematics at NUI Galway. After graduating with a bachelor's in Mathematical Sciences
  I moved to Vienna (Austria) to pursue a master's degree in quantitative finance. I was excited to apply the many mathematical and 
  computational concepts that I have learned over the years to the fascinating world of finance. After attaining a master's degree 
  in quant finance, I wanted to learn a little bit more about data science, machine learning and advanced statistical methods. I 
  also saw how applicable and relevant these methods are becoming for the realm of quant finance. This motivated me to pursue a 
  1-year master's degree in Data and Computational Science at the University College Dublin. I am currently enrolled in this programme and
  I am looking for employment opportunities. Feel free to reach out! Have a good day :)

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Master Thesis 
        # link: github.com/sproogen
        # # link_text: Project Website
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is the thesis that I wrote as part of the master's degree in quantitative finance.
        description: | # this will include new lines to allow paragraphs
          This master's thesis examines firm-level contemporaneous and lagged relationships between
          Tweet-based features (i.e., Twitter activity and sentiment polarity) and stock market 
          characteristics (i.e., holding period return and trading volume) at daily frequency. 
          Our findings support the existence of contemporaneous association between Twitter mood 
          and returns (turnover), together with the relation of Tweet volume and returns (turnover). 
          Furthermore, we established that investor agreement and Tweet volume could be of use in predicting abnormal 
          trading volume on the following day. In contrast to previous closely related research, we found no indication of 
          Twitter-based investor sentiment and interest being helpful in predicting returns, which was subsequently reflected 
          in the underwhelming performance of the corresponding long-short portfolios. Nevertheless, we observed that aggregation 
          of firm-level Twitter sentiment can be beneficial in forecasting the performance of ETFs, stock indices and portfolios.

          You can download my thesis [here](assets/thesis.pdf) and the correpsonding presentation [here](assets/presentation.pdf). 

  - title: Experience and Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        #title: 
        # link: boringcompany.com
        # # link_text: boringcompany.com
        # sub_title: Senior Network System Administrator
        # caption: November 2017 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            You can download my [Resume/CV](assets/CV.pdf).

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in quantitative finance, data science and programming, some of my other interests and hobbies are:
      - Hiking ğŸ¥¾ğŸ”ï¸
      - Music (Singing, Ukulele) ğŸ¼
      - Baking ğŸ§
      - Film Photography ğŸ“¸

      Here are some recent picture that I took
      
      | Image 1 | Image 2 |
      |---------|---------|
      | ![Alt Text 1](images/profile.jpg) | ![Alt Text 2](images/profile.jpg) |
      | Image 3 | Image 4 |
      |---------|---------|
      | ![Alt Text 3](images/profile.jpg) | ![Alt Text 4](images/profile.jpg) |
      | Image 5 | Image 6 |
      |---------|---------|
      | ![Alt Text 5](images/profile.jpg) | ![Alt Text 6](images/profile.jpg) |

  


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
